language:
  elixir

env:
  global:
    - MIX_ENV=test

matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.5
    - otp_release: 19.3
      elixir: 1.4.5

    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 20.2
      elixir: 1.5.3

    - otp_release: 20.2
      elixir: 1.6.1

script:
  - mix do deps.compile, compile
  - >
    if [[ "${TRAVIS_ELIXIR_VERSION}" == "1.6.1" ]]; then
      mix format mix.exs lib/**/*.{ex,exs} --check-formatted && \
      mix format mix.exs test/**/*.{ex,exs} --check-formatted
    fi;
#  - mix credo --strict --ignore maxlinelength,cyclomaticcomplexity,todo
  - mix test
  - mix coveralls
